package com.example.myimmo2.data.repository

import com.example.myimmo2.data.SupabaseClient
import com.example.myimmo2.data.model.City
import com.example.myimmo2.data.model.Neighborhood
import com.example.myimmo2.data.model.Region
import io.github.jan.supabase.postgrest.postgrest
import io.github.jan.supabase.postgrest.query.Columns

class LocationRepository {

    suspend fun getRegions(): List<Region> {
        return SupabaseClient.client.postgrest.from("regions").select().decodeList<Region>()
    }

    suspend fun getCities(regionId: String): List<City> {
        return SupabaseClient.client.postgrest.from("cities").select { filter { eq("region_id", regionId) } }.decodeList<City>()
    }

    suspend fun getNeighborhoods(cityId: String): List<Neighborhood> {
        return SupabaseClient.client.postgrest.from("neighborhoods").select { filter { eq("city_id", cityId) } }.decodeList<Neighborhood>()
    }

    suspend fun addCity(cityName: String, regionId: String): City {
        val city = City(id = "", regionId = regionId, name = cityName) // ID will be generated by Supabase
        return SupabaseClient.client.postgrest.from("cities").insert(city, returning = Columns.REPRESENTATION).decodeSingle<City>()
    }

    suspend fun addNeighborhood(neighborhoodName: String, cityId: String): Neighborhood {
        val neighborhood = Neighborhood(id = "", cityId = cityId, name = neighborhoodName) // ID will be generated by Supabase
        return SupabaseClient.client.postgrest.from("neighborhoods").insert(neighborhood, returning = Columns.REPRESENTATION).decodeSingle<Neighborhood>()
    }
}
